datadir: 'data/KNMI.txt.tsv'
data_eeg: '/homes/ahvandenbroek/Documents/Prog1 data processing/BFVM22PROG1/study_cases/data/eeg_data.csv'
data_glucose: '/homes/ahvandenbroek/Documents/Prog1 data processing/BFVM22PROG1/study_cases/data/glucose.json'
data_careplans: '/homes/ahvandenbroek/Documents/Prog1 data processing/BFVM22PROG1/study_cases/data/careplans.csv'
data_conditions: '/homes/ahvandenbroek/Documents/Prog1 data processing/BFVM22PROG1/study_cases/data/conditions.csv'
data_encounters: '/homes/ahvandenbroek/Documents/Prog1 data processing/BFVM22PROG1/study_cases/data/encounters.csv'
data_patients: '/homes/ahvandenbroek/Documents/Prog1 data processing/BFVM22PROG1/study_cases/data/patients.csv'
data_observations: '/homes/ahvandenbroek/Documents/Prog1 data processing/BFVM22PROG1/study_cases/data/observations.csv'
data_knmi: '/homes/ahvandenbroek/Documents/Prog1 data processing/BFVM22PROG1/study_cases/data/KNMI_20181231.txt.tsv'